name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - ci
  release:
    types: [published]

jobs:
  deploy-pages:
    #needs: build-and-push
    runs-on: mathiasvda/yasgui:latest # there should be a better way to do this
    steps:
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: /usr/share/nginx/html/
